[metadata]
name = ai_commit_hooks
version = 1.0.0
description = AI-powered Git commit message generator hook for pre-commit.
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/mcocdaa/ai-commit
license = MIT
license_files = LICENSE
classifiers =
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3 :: Only

[options]
packages = find:
python_requires = >=3.9

[options.packages.find]
exclude =
    tests*
    testing*

[options.entry_points]
console_scripts =
    ai-commit-gen = prepare_commit_msg_hooks.ai_commit_gen:main
